export const ErrorCodes = {
    INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
    UNAUTHORIZED: 'UNAUTHORIZED',
    NOT_FOUND: 'NOT_FOUND',
    EMAIL_IN_USE: 'EMAIL_IN_USE',
    EMAIL_ALREADY_VERIFIED: 'EMAIL_ALREADY_VERIFIED',
    PASSWORD_ALREADY_CHANGED: 'PASSWORD_ALREADY_CHANGED',
    TOKEN_EXPIRED: 'TOKEN_EXPIRED',
    VALIDATION_FAILED: 'VALIDATION_FAILED',
    ALREADY_VERIFIED: 'ALREADY_VERIFIED',
    INVALID_VALUE: 'INVALID_VALUE',
    INVALID_CODE: 'INVALID_CODE',
    USER_NOT_FOUND: 'USER_NOT_FOUND',
    USER_EXPIRED: 'USER_EXPIRED',
    INVALID_TOKEN_TYPE: 'INVALID_TOKEN_TYPE',
    CANNOT_MODIFY: 'CANNOT_MODIFY',
    INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes]
